alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
databases:
- engine: PG
  name: db
  num_nodes: 1
  size: db-s-dev-database
  version: "12"
envs:
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
- key: DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "0"
- key: DJANGO_ALLOWED_HOST
  scope: RUN_AND_BUILD_TIME
  value: .ondigitalocean.app
- key: DJANGO_SECRET_KEY
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:QTDlQJEsqsJWJ9uJrU2xg0D6X6gAHqte:xMT+xdEd9tZNCj00KpEmwT6PwhGSa/682ln59qVnJDYpPAb0XZpgOB6Oh+yWZTGjyM3SowDqQbms1DZXm6n1cDj+]
- key: DJANGO_SUPERUSER_EMAIL
  scope: RUN_AND_BUILD_TIME
  value: prasannavenkatesh918@gmail.com
- key: DJANGO_SUPERUSER_USERNAME
  scope: RUN_AND_BUILD_TIME
  value: prasanna
- key: DJANGO_SUPERUSER_PASSWORD
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:w3MtMMMgjrGyC0FbI+MAGNVIR9rfsgpn:7SlZXKcho3z42XUgIqbMafXcFTrW1zeqvZRUGiazzXhrxXRglDenxUci2aBcjb1s567n+xHkSRgNcp8EVfp/pcuv]
- key: POSTGRES_DB
  scope: RUN_AND_BUILD_TIME
  value: ${db.DATABASE}
- key: POSTGRES_HOST
  scope: RUN_AND_BUILD_TIME
  value: ${db.HOSTNAME}
- key: POSTGRES_USER
  scope: RUN_AND_BUILD_TIME
  value: ${db.USERNAME}
- key: POSTGRES_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: ${db.PASSWORD}
- key: POSTGRES_PORT
  scope: RUN_AND_BUILD_TIME
  value: ${db.PORT}
jobs:
- environment_slug: python
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  github:
    branch: production-1
    deploy_on_push: true
    repo: mynamasp/Try-Django-3.2
  instance_count: 1
  instance_size_slug: basic-xxs
  kind: PRE_DEPLOY
  name: django-migrate
  run_command: |-
    gunicorn --worker-tmp-dir /dev/shm
    python manage.py migrate --noinput
    python manage.py createsuperuser --noinput --email prasannavenkatesh918@gmail.com
  source_dir: /
name: try-django-3-2
region: blr
services:
- environment_slug: python
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  github:
    branch: production-1
    deploy_on_push: true
    repo: mynamasp/Try-Django-3.2
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: try-django-3-2
  routes:
  - path: /
  run_command: gunicorn --worker-tmp-dir /dev/shm trydjango.wsgi
  source_dir: /
